//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LE_Formatter.lang {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Loc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Loc() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LE_Formatter.lang.Loc", typeof(Loc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die One or more LE files could not be removed from your &quot;The Sims 4&quot; folder. You may want to remove them yourself.
        ///Open &quot;The Sims 4&quot; folder now? ähnelt.
        /// </summary>
        public static string DialogueClearLesError {
            get {
                return ResourceManager.GetString("DialogueClearLesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The following code exception has occured:
        ///Thread: {0}
        ///{1} ähnelt.
        /// </summary>
        public static string DialogueCodeException {
            get {
                return ResourceManager.GetString("DialogueCodeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The following .ts4script file or .zip file may be corrupt.
        ///File: {0}
        ///If you were just downloading this file then you shouldn&apos;t have to worry, just manually re-index after your download has finished and you have extracted the necessary files. Otherwise you may wish to delete this file. This message will only be shown once for this file. ähnelt.
        /// </summary>
        public static string DialogueCorruptZip {
            get {
                return ResourceManager.GetString("DialogueCorruptZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string DialogueGeneralError {
            get {
                return ResourceManager.GetString("DialogueGeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file that was attempted to be loaded did not contain a valid LE call stack.
        ///File: {0} ähnelt.
        /// </summary>
        public static string DialogueLoadLeContainsNoLEInside {
            get {
                return ResourceManager.GetString("DialogueLoadLeContainsNoLEInside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The LE file that was attempted to be loaded could not loaded.
        ///File: {0}
        ///Error: {1} ähnelt.
        /// </summary>
        public static string DialogueLoadLeCouldNotLoad {
            get {
                return ResourceManager.GetString("DialogueLoadLeCouldNotLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error on trying to load LE file ähnelt.
        /// </summary>
        public static string DialogueLoadLeGeneralError {
            get {
                return ResourceManager.GetString("DialogueLoadLeGeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file that was attempted to be loaded does not seem to be a valid XML file and as such not an LE file.
        ///File: {0}
        ///Error: {1} ähnelt.
        /// </summary>
        public static string DialogueLoadLeNotXML {
            get {
                return ResourceManager.GetString("DialogueLoadLeNotXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not read settings file.
        ///Error: {0}
        ///
        ///Abort program? ähnelt.
        /// </summary>
        public static string DialogueSettingsFileError {
            get {
                return ResourceManager.GetString("DialogueSettingsFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings error ähnelt.
        /// </summary>
        public static string DialogueSettingsGeneralError {
            get {
                return ResourceManager.GetString("DialogueSettingsGeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The path to your &quot;The Sims 4&quot; folder and/or the path to your game installation could not be identified.
        ///Go to the settings and set them manually. ähnelt.
        /// </summary>
        public static string DialogueSettingsPathsNull {
            get {
                return ResourceManager.GetString("DialogueSettingsPathsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The provided path does seem to be a game installation directory. However, there were no base game scripts found.
        ///Try repairing (EA) or verifying (Steam) your game files. ähnelt.
        /// </summary>
        public static string DialogueVerifyInstallFolderNoPythonZips {
            get {
                return ResourceManager.GetString("DialogueVerifyInstallFolderNoPythonZips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The provided path does not seem to a game installation directory, as its subdirectories do not reflect that of one. ähnelt.
        /// </summary>
        public static string DialogueVerifyInstallFolderSubfolderError {
            get {
                return ResourceManager.GetString("DialogueVerifyInstallFolderSubfolderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The path provided does not actually seem to exist. ähnelt.
        /// </summary>
        public static string DialogueVerifyPathDoesNotExist {
            get {
                return ResourceManager.GetString("DialogueVerifyPathDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The provided path does not seem to resemble the &quot;The Sims 4&quot; directory as it either contains no &quot;Mods&quot; folder or the &quot;GameVersion.txt&quot; file. ähnelt.
        /// </summary>
        public static string DialogueVerifyTs4DocumentsFolderSubfolderError {
            get {
                return ResourceManager.GetString("DialogueVerifyTs4DocumentsFolderSubfolderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select a Folder ähnelt.
        /// </summary>
        public static string GenericDialogueSelectFolder {
            get {
                return ResourceManager.GetString("GenericDialogueSelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Czech (Čeština) ähnelt.
        /// </summary>
        public static string GenericLanguage_cs_CZ {
            get {
                return ResourceManager.GetString("GenericLanguage_cs_CZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Danish (Dansk) ähnelt.
        /// </summary>
        public static string GenericLanguage_da_DK {
            get {
                return ResourceManager.GetString("GenericLanguage_da_DK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die German (Deutsch) ähnelt.
        /// </summary>
        public static string GenericLanguage_de_AT {
            get {
                return ResourceManager.GetString("GenericLanguage_de_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die English ähnelt.
        /// </summary>
        public static string GenericLanguage_en_US {
            get {
                return ResourceManager.GetString("GenericLanguage_en_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spanish (Español) ähnelt.
        /// </summary>
        public static string GenericLanguage_es_ES {
            get {
                return ResourceManager.GetString("GenericLanguage_es_ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Finnish (Suomi) ähnelt.
        /// </summary>
        public static string GenericLanguage_fi_FI {
            get {
                return ResourceManager.GetString("GenericLanguage_fi_FI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die French (Français) ähnelt.
        /// </summary>
        public static string GenericLanguage_fr_FR {
            get {
                return ResourceManager.GetString("GenericLanguage_fr_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Italian (Italiano) ähnelt.
        /// </summary>
        public static string GenericLanguage_it_IT {
            get {
                return ResourceManager.GetString("GenericLanguage_it_IT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Japanese (日本語) ähnelt.
        /// </summary>
        public static string GenericLanguage_ja_JP {
            get {
                return ResourceManager.GetString("GenericLanguage_ja_JP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Korean (한국어) ähnelt.
        /// </summary>
        public static string GenericLanguage_ko_KR {
            get {
                return ResourceManager.GetString("GenericLanguage_ko_KR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Norwegian - Bokmål (Norsk - Bokmål) ähnelt.
        /// </summary>
        public static string GenericLanguage_nb_NO {
            get {
                return ResourceManager.GetString("GenericLanguage_nb_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dutch (Nederlands) ähnelt.
        /// </summary>
        public static string GenericLanguage_nl_NL {
            get {
                return ResourceManager.GetString("GenericLanguage_nl_NL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Polish (Polszczyzna) ähnelt.
        /// </summary>
        public static string GenericLanguage_pl_PL {
            get {
                return ResourceManager.GetString("GenericLanguage_pl_PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Portuguese - Brazil (Português Brasileiro) ähnelt.
        /// </summary>
        public static string GenericLanguage_pt_BR {
            get {
                return ResourceManager.GetString("GenericLanguage_pt_BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Russian (Русский) ähnelt.
        /// </summary>
        public static string GenericLanguage_ru_RU {
            get {
                return ResourceManager.GetString("GenericLanguage_ru_RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Swedish (Svenska) ähnelt.
        /// </summary>
        public static string GenericLanguage_sv_SE {
            get {
                return ResourceManager.GetString("GenericLanguage_sv_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chinese - Simplified (汉语) ähnelt.
        /// </summary>
        public static string GenericLanguage_zh_CN {
            get {
                return ResourceManager.GetString("GenericLanguage_zh_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chinese - Traditional (漢語) ähnelt.
        /// </summary>
        public static string GenericLanguage_zh_TW {
            get {
                return ResourceManager.GetString("GenericLanguage_zh_TW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Re-index Mods ähnelt.
        /// </summary>
        public static string IndexFilesButton {
            get {
                return ResourceManager.GetString("IndexFilesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use this when adding new script mods and not having automatic re-indexing enabled. ähnelt.
        /// </summary>
        public static string IndexFilesButtonLabel {
            get {
                return ResourceManager.GetString("IndexFilesButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This page shows the script file paths that should be loaded by the Sims 4, separated by their origin. Some script may not be shown here, as they may be generated only when the game is running or are in general not accessible outside the game.
        ///
        ///Note, that while some of the script paths may look like file paths, they will usually not actually exist on your own computer. Usually these paths are the file paths at the time the modder is packaging the mod. ähnelt.
        /// </summary>
        public static string IndexFilesDescription {
            get {
                return ResourceManager.GetString("IndexFilesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Contained script file paths ähnelt.
        /// </summary>
        public static string IndexFilesEntryLabelContained {
            get {
                return ResourceManager.GetString("IndexFilesEntryLabelContained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Path ähnelt.
        /// </summary>
        public static string IndexFilesEntryLabelPath {
            get {
                return ResourceManager.GetString("IndexFilesEntryLabelPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type ähnelt.
        /// </summary>
        public static string IndexFilesEntryLabelType {
            get {
                return ResourceManager.GetString("IndexFilesEntryLabelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loose &quot;Scripts&quot; folder with scripts ähnelt.
        /// </summary>
        public static string IndexFilesEntryTypeFolder {
            get {
                return ResourceManager.GetString("IndexFilesEntryTypeFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die .ts4script or .zip file ähnelt.
        /// </summary>
        public static string IndexFilesEntryTypeZipped {
            get {
                return ResourceManager.GetString("IndexFilesEntryTypeZipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aggregation of multiple zipped files ähnelt.
        /// </summary>
        public static string IndexFilesEntryTypeZippedMultiple {
            get {
                return ResourceManager.GetString("IndexFilesEntryTypeZippedMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete available LE files ähnelt.
        /// </summary>
        public static string LeFileTabButtonClearLes {
            get {
                return ResourceManager.GetString("LeFileTabButtonClearLes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load available LE files ähnelt.
        /// </summary>
        public static string LeFileTabButtonLoadRecentLes {
            get {
                return ResourceManager.GetString("LeFileTabButtonLoadRecentLes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Traceback ähnelt.
        /// </summary>
        public static string LeFileTabContentLabelCallStack {
            get {
                return ResourceManager.GetString("LeFileTabContentLabelCallStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Script Exception Message ähnelt.
        /// </summary>
        public static string LeFileTabContentLabelExceptionMessage {
            get {
                return ResourceManager.GetString("LeFileTabContentLabelExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In-game Exception Message ähnelt.
        /// </summary>
        public static string LeFileTabContentLabelInGameMessage {
            get {
                return ResourceManager.GetString("LeFileTabContentLabelInGameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can double click on a row to open the path to the mod listed in the Origin column. ähnelt.
        /// </summary>
        public static string LeFileTabContentTextBoxCallStackDescriptionAfterHyperlink {
            get {
                return ResourceManager.GetString("LeFileTabContentTextBoxCallStackDescriptionAfterHyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bottom-most entries of the traceback happened closer to the exception. This doesn&apos;t mean that the bottom-most mentioned mod must be the cause of the exception. It only means that the mod&apos;s script was called closer to when the exception happened. ähnelt.
        /// </summary>
        public static string LeFileTabContentTextBoxCallStackDescriptionGeneral {
            get {
                return ResourceManager.GetString("LeFileTabContentTextBoxCallStackDescriptionGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die For more information click ähnelt.
        /// </summary>
        public static string LeFileTabContentTextBoxCallStackDescriptionHyperlink1 {
            get {
                return ResourceManager.GetString("LeFileTabContentTextBoxCallStackDescriptionHyperlink1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die here ähnelt.
        /// </summary>
        public static string LeFileTabContentTextBoxCallStackDescriptionHyperlink2 {
            get {
                return ResourceManager.GetString("LeFileTabContentTextBoxCallStackDescriptionHyperlink2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die . ähnelt.
        /// </summary>
        public static string LeFileTabContentTextBoxCallStackDescriptionHyperlink3 {
            get {
                return ResourceManager.GetString("LeFileTabContentTextBoxCallStackDescriptionHyperlink3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Script file ähnelt.
        /// </summary>
        public static string LeFileTabDataGridFile {
            get {
                return ResourceManager.GetString("LeFileTabDataGridFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Line ähnelt.
        /// </summary>
        public static string LeFileTabDataGridLine {
            get {
                return ResourceManager.GetString("LeFileTabDataGridLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Origin ähnelt.
        /// </summary>
        public static string LeFileTabDataGridOrigin {
            get {
                return ResourceManager.GetString("LeFileTabDataGridOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Script Call ähnelt.
        /// </summary>
        public static string LeFileTabDataGridScriptCall {
            get {
                return ResourceManager.GetString("LeFileTabDataGridScriptCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LE files can be dragged-and-dropped here. ähnelt.
        /// </summary>
        public static string LeFileTabDragAndDrop {
            get {
                return ResourceManager.GetString("LeFileTabDragAndDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Functions for manual operation ähnelt.
        /// </summary>
        public static string LeFileTabLabelButtonOperators {
            get {
                return ResourceManager.GetString("LeFileTabLabelButtonOperators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This LE has been taken from MCCC&apos;s report. It doesn&apos;t contain the in-game exception message. ähnelt.
        /// </summary>
        public static string LeFileTabMcccWarning {
            get {
                return ResourceManager.GetString("LeFileTabMcccWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Sims 4 ähnelt.
        /// </summary>
        public static string LeFileTabOriginTheSims4 {
            get {
                return ResourceManager.GetString("LeFileTabOriginTheSims4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown ähnelt.
        /// </summary>
        public static string LeFileTabOriginUnknown {
            get {
                return ResourceManager.GetString("LeFileTabOriginUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If this option and &quot;Auto-Open latest LE file&quot; are both enabled, the program will force its window in front of other applications&apos; (including TS4&apos;s) when opening an LE file.
        ///Useful if you only have a single monitor. ähnelt.
        /// </summary>
        public static string SettingsAutoOpenLatestBringToFrontDescription {
            get {
                return ResourceManager.GetString("SettingsAutoOpenLatestBringToFrontDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bring to Front on Auto-Open ähnelt.
        /// </summary>
        public static string SettingsAutoOpenLatestBringToFrontLabel {
            get {
                return ResourceManager.GetString("SettingsAutoOpenLatestBringToFrontLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If enabled automatically opens the latest LE file while the program is running.
        ///All open LE files will also be closed when you start The Sims 4, so you don&apos;t have any old LEs open. ähnelt.
        /// </summary>
        public static string SettingsAutoOpenLatestDescription {
            get {
                return ResourceManager.GetString("SettingsAutoOpenLatestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatically open LE files ähnelt.
        /// </summary>
        public static string SettingsAutoOpenLatestLabel {
            get {
                return ResourceManager.GetString("SettingsAutoOpenLatestLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If enabled automatically re-indexes your script mods when changes happen in your Mods folder. Makes you not have to manually re-index your mods on the &quot;Script Index&quot; page. ähnelt.
        /// </summary>
        public static string SettingsAutoReIndexDescription {
            get {
                return ResourceManager.GetString("SettingsAutoReIndexDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto Re-index Mods ähnelt.
        /// </summary>
        public static string SettingsAutoReIndexLabel {
            get {
                return ResourceManager.GetString("SettingsAutoReIndexLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change ähnelt.
        /// </summary>
        public static string SettingsButtonChangePath {
            get {
                return ResourceManager.GetString("SettingsButtonChangePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Application language. Some texts may still be in the language set at startup until the associated UI elements are reloaded or the program is restarted. ähnelt.
        /// </summary>
        public static string SettingsLanguageDescription {
            get {
                return ResourceManager.GetString("SettingsLanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        public static string SettingsLanguageLabel {
            get {
                return ResourceManager.GetString("SettingsLanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Path to your &quot;The Sims 4&quot; folder, that also contains the &quot;Mods&quot; folder that your mods are kept in.
        ///Normally found in:
        ///User folder -&gt; &quot;Documents&quot; -&gt; &quot;Electronic Arts&quot; -&gt; &quot;The Sims 4&quot;
        ///
        ///Depending on your in-game language, the &quot;The Sims 4&quot; folder may be translated to that language. ähnelt.
        /// </summary>
        public static string SettingsTS4FolderDescription {
            get {
                return ResourceManager.GetString("SettingsTS4FolderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;The Sims 4&quot; Folder Path ähnelt.
        /// </summary>
        public static string SettingsTS4FolderLabel {
            get {
                return ResourceManager.GetString("SettingsTS4FolderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The folder where your game installation is located.
        ///This folder should contain various subfolders, such as &quot;Game&quot;, &quot;Data&quot;, as well as folders for DLC labeled like &quot;EP01&quot;, &quot;GP03&quot; or &quot;SP06&quot;. ähnelt.
        /// </summary>
        public static string SettingsTS4InstallationFolderDescription {
            get {
                return ResourceManager.GetString("SettingsTS4InstallationFolderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Sims 4 Installation Folder Path ähnelt.
        /// </summary>
        public static string SettingsTS4InstallationFolderLabel {
            get {
                return ResourceManager.GetString("SettingsTS4InstallationFolderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Script Index ähnelt.
        /// </summary>
        public static string TabIndexFiles {
            get {
                return ResourceManager.GetString("TabIndexFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LE Files ähnelt.
        /// </summary>
        public static string TabLeFile {
            get {
                return ResourceManager.GetString("TabLeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string TabSettings {
            get {
                return ResourceManager.GetString("TabSettings", resourceCulture);
            }
        }
    }
}
